[build]
  command = "npm run build"
  publish = "dist/maos-que-cuidam/browser"

[build.environment]
  NODE_VERSION = "20"
  DISABLE_NETLIFY_DRAWER = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
